---
- name: Include registry tasks
  include: registry.yml
  tags: registry
  when: enable_registry

- name: Include nfs-server tasks
  include: nfs-server.yml
  tags: nfs-server
  when: enable_nfs_server

- name: Include openldap tasks
  include: openldap.yml
  tags: openldap
  when: enable_openldap

- name: Include minio tasks
  include: minio.yml
  tags: minio
  when: enable_minio
