---
- name: minio - create data directory
  file:
    state: directory
    path: /opt/minio-data
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: true

- name: minio - pull image
  docker_image:
    name: "{{ minio_image }}"

- name: minio - start container
  docker_container:
    name: minio
    image: "{{ minio_image }}"
    state: started
    recreate: yes
    restart_policy: always
    environment:
      MINIO_ACCESS_KEY: "{{ minio_access_key }}"
      MINIO_SECRET_KEY: "{{ minio_secret_key }}"
      MINIO_REGION: "{{ minio_region }}"
    entrypoint: "server /export"
    volumes:
      - "/opt/minio-data:/export"
    published_ports:
      - "{{ minio_host }}:{{ minio_port }}:9000"
