---
- name: nfs-server - create data directory
  file:
    state: directory
    path: /opt/nfs-server-data
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: true

- name: nfs-server - create export directories
  file:
    state: directory
    path: "/opt/nfs-server-data/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  with_items: "{{ nfs_server_exports }}"

- name: nfs-server - pull image
  docker_image:
    name: "{{ nfs_server_image }}"

- name: nfs-server - start container
  docker_container:
    name: nfs-server
    image: "{{ nfs_server_image }}"
    state: started
    recreate: yes
    restart_policy: always
    volumes:
      - "/opt/nfs-server-data:/exports"
    published_ports:
      - "{{ nfs_server_host }}:111:111/udp"
      - "{{ nfs_server_host }}:2049:2049/tcp"
