---
- name: openldap - create directories
  file:
    state: directory
    path: "/opt/openldap-{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  with_items:
    - data
    - configuration
  become: true

- name: openldap - copy configuration
  template:
    src: openldap/custom.yaml.j2
    dest: /opt/openldap-configuration/custom.yaml
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: false

- name: openldap - copy ldif file
  template:
    src: openldap/scheme.ldif.j2
    dest: /opt/openldap-data/scheme.ldif
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: false

- name: openldap - pull image
  docker_image:
    name: "{{ openldap_image }}"

- name: openldap - start container
  docker_container:
    name: openldap
    image: "{{ openldap_image }}"
    state: started
    recreate: yes
    restart_policy: always
    volumes:
      - "/opt/openldap-configuration:/container/environment/01-custom:ro"
    published_ports:
      - "{{ openldap_host }}:{{ openldap_port }}:389"

- name: openldap - pull phpldapadmin image
  docker_image:
    name: "{{ phpldapadmin_image }}"

- name: openldap - start phpldapadmin container
  docker_container:
    name: phpldapadmin
    image: "{{ phpldapadmin_image }}"
    state: started
    recreate: yes
    restart_policy: always
    published_ports:
      - "{{ openldap_host }}:{{ openldap_port_webinterface }}:443"
    links:
      - openldap:openldap
    env:
      PHPLDAPADMIN_LDAP_HOSTS: openldap

- name: openldap - install ldap-utils package
  package:
    name: ldap-utils
    state: present
  become: true
  when: "ansible_os_family == 'Debian'"

- name: openldap - install openldap-clients package
  package:
    name: openldap-clients
    state: present
  become: true
  when: "ansible_os_family == 'RedHat'"

- name: openldap - import testing data
  shell: "ldapadd -x -c -w {{ openldap_admin_password }} -D 'cn=admin,dc=betacloud,dc=io' -f /opt/openldap-data/scheme.ldif -H ldap://{{ openldap_host }} || true"
  changed_when: false
